[project]
name = "betregret"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KaanKayali", email = "citrusshooter1980@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.2.15",
    "langchain-mcp-adapters>=0.2.2",
    "langchain-openai>=1.1.12",
    "python-dotenv>=1.2.2",
    "langgraph",
    "mcp[cli]",
    "pandas",
    "pydantic",
]

[project.scripts]
betregret = "betregret:main"

[build-system]
requires = ["uv_build>=0.10.3,<0.11.0"]
build-backend = "uv_build"
